### GENERAL SETTINGS ###

# Site settings
title: KIXLAB
description: "The KAIST Interaction Lab (KIXLAB) focuses on human-computer interaction research in the School of Computing at KAIST. We build interactive systems that support interaction at scale: crowdsourcing and human computation, online education and learning at scale, civic engagement and collective action, and interactive data analytics and mining. We often take an interdisciplinary approach to our research, by connecting computer science with learning science, psychology, and sociology, and aim to deploy our systems to real users."
analytics: UA-50546869-2
baseurl: "" #important: start with /
url: "http://kixlab.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#000000" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#ffa500"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
<<<<<<< HEAD
#social:
#  - title: dribbble
#    url:
#  - title: facebook
#    url:
#  - title: twitter
#    url: 
#  - title: instagram
#    url: 
#  - title: tumblr
#    url: 
    
=======
>>>>>>> master
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 34141 Daejeon Yuseonggu Daehakro 291 
    - KAIST N1 624
<<<<<<< HEAD
    - 291 Daehak-ro, Yuseong-gu, Daejeon 34141
    - Republic of Korea
=======
>>>>>>> master
email: kixlab@kixlab.org
tel: "+82 42 350 7865"


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
# If member changed --> modify in here
members:
    ## current members
    # 
    #       
    #
    - stateObj: 
        statename: CURRENT MEMBERS
        position:
            - positionName: Professor
              positionMembers:
                - name: Juho Kim
                  email: juhokim@juhokim.com
                  career:
                    - 
                  img: team01.jpg 
            - positionName: Ph.D Students
                  interest: KIXLAB
              positionMembers:
                - name: Minsuk Chang
                  email:
                  career: 
                  img: team01.jpg 
            - positionName: MS Students
                  interest: KIXLAB
              positionMembers:
            - positionName: Undergraduates
              positionMembers:
                - name: Jiwoo Park
                  email: jiwoojoajoa@gmail.com
                  career: 
                    - elementary
                  interest: KIXLAB
                  img: team01.jpg 
                - name: Hyungyu Shin
                  email: hyungyu.sh@kaist.ac.kr
                  career: 
					- BS, Dept. of CSE, POSTECH
                  img: team01.jpg 
                - name: Dongkwan Kim
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
                - name: Hyeongshik Jeong
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
                - name: Taekyung Park
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
 
    ## Members who leave KIXLAB
    - stateObj:
        statename: ALUMNI
        statemembers:
            - name: Alumni1
              position: Working
              text: CEO
              img: team04.jpg
              state: sdf
            - name: Alumni2
              position: Working
              text: CEO2
              img: team02.jpg
              state: Cool
      
<<<<<<< HEAD
# Clients information. Shown on Home and About pages.
clients:
  - name: KAIST
    img: client01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We pursue a society where humans and computers really understand each other."

=======
### Publications
publications:
    -where:
        whereName: Journal
        -class:
            className: International
            classPapers:
                -
        -class:
            className: Domestic
    -where:
        whereName: Conference
        papers:
    -where:
        whereName: Others
                 
>>>>>>> master
# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Welcome to KIXLAB. We are a human computer interaction research group."
    author: Jiwoo Park
    position: Web Page Designer
