### GENERAL SETTINGS ###

# Site settings
title: KIXLAB
description: "The KAIST Interaction Lab (KIXLAB) focuses on human-computer interaction research in the School of Computing at KAIST. We build interactive systems that support interaction at scale: crowdsourcing and human computation, online education and learning at scale, civic engagement and collective action, and interactive data analytics and mining. We often take an interdisciplinary approach to our research, by connecting computer science with learning science, psychology, and sociology, and aim to deploy our systems to real users."
analytics: UA-50546869-2
baseurl: "" #important: start with /
url: "http://kixlab.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FFDB0D" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#FF8C00"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - KAIST N1 624
    - 291 Daehak-ro, Yuseong-gu, Daejeon 34141
    - Republic of Korea
email: kixlab@kixlab.org
tel: "+82 42 350 7865"


### GENERAL DATA FOR VARIOUS LOCATIONS ###



# Clients information. Shown on Home and About pages.
clients:
  - name: KAIST
    img: client01.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We pursue a society where humans and computers really understand each other."

# Testimonial content. Shown on Home and About page.
testmonial:
  message: "Machinelearning is also learning"
  author: Minsuk Chang
  position: Ph.D. candidate
#testimonial:
#    message: "The KAIST Interaction Lab (KIXLAB) focuses on human-computer interaction research in the School of Computing at KAIST. We build interactive systems that support interaction at scale: crowdsourcing and human computation, online education and learning at scale, civic engagement and collective action, and interactive data analytics and mining. We often take an interdisciplinary approach to our research, by connecting computer science with learning science, psychology, and sociology, and aim to deploy our systems to real users"
    #author: Jiwoo Park
    #position: Web Page Designer
