### GENERAL SETTINGS ###

# Site settings
title: KIXLAB
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: UA-50546869-2
baseurl: "" #important: start with /
url: "http://kixlab.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#000000" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 34141 Daejeon Yuseonggu Daehakro 291 
    - KAIST N1 624
email: kixlab@kixlab.org
tel: "TBD"


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
# If member changed --> modify in here
members:
    ## current members
    # 
    #       
    #
    - stateObj: 
        statename: CURRENT MEMBERS
        position:
            - positionName: Professor
              positionMembers:
                - name: Juho Kim
                  email: juhokim@juhokim.com
                  career:
                    - 
                  img: team01.jpg 
                  interest: KIXLAB
            - positionName: Ph.D Candidates
              positionMembers:
                - name: Minsuk Jang
                  email: enter later
                  career: enter later
                  img: team01.jpg 
                  interest: KIXLAB
            - positionName: MS Candidates
              positionMembers:
            - positionName: Undergraduates
              positionMembers:
                - name: Jiwoo Park
                  email: jiwoojoajoa@gmail.com
                  career: 
                    - elementary
                  interest: KIXLAB
                  img: team01.jpg 
                - name: Hyungyu Shin
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
                - name: Dongkwan Kim
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
                - name: Hyeongshik Jeong
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
                - name: Taekyung Park
                  email: <enter later>
                  career: <later>
                  img: team01.jpg 
 
    ## Members who leave KIXLAB
    - stateObj:
        statename: ALUMNI
        statemembers:
            - name: Alumni1
              position: Working
              text: CEO
              img: team04.jpg
              state: sdf
            - name: Alumni2
              position: Working
              text: CEO2
              img: team02.jpg
              state: Cool
      
### Publications
publications:
    -where:
        whereName: Journal
        -class:
            className: International
            classPapers:
                -
        -class:
            className: Domestic
    -where:
        whereName: Conference
        papers:
    -where:
        whereName: Others
                 
# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Welcome to KIXLAB. We pursue human computer interaction."
    author: Jiwoo Park
    position: Web Page Designer
